import React from 'react';

export const Footer: React.FC = () => (
  <footer className="bg-slate-900 text-slate-300 py-12 border-t border-slate-800">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-3 gap-8">
      <div>
        <h4 className="text-white text-lg font-bold mb-4">AMAR DESH</h4>
        <p className="text-sm leading-relaxed text-slate-400">
          Your AI-powered companion for exploring the natural beauty, heritage, and rich culture of Bangladesh.
        </p>
      </div>
      <div>
        <h4 className="text-white text-lg font-bold mb-4">Important Disclaimer</h4>
        <p className="text-sm leading-relaxed text-slate-400">
          Our information is generated by AI and is approximately 90% accurate. Details regarding prices, transport schedules, safety situations, and local conditions may change rapidly. We strongly advise verifying critical details with local authorities or guides before traveling.
        </p>
      </div>
      <div>
         <h4 className="text-white text-lg font-bold mb-4">Quick Links</h4>
         <ul className="text-sm text-slate-400 space-y-2">
            <li>National Emergency Helpline: 999</li>
            <li>Tourist Police: +880 1320-222222</li>
            <li><a href="#" className="hover:text-teal-400 transition-colors">Privacy Policy</a></li>
            <li><a href="#" className="hover:text-teal-400 transition-colors">Terms of Service</a></li>
         </ul>
      </div>
    </div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12 pt-8 border-t border-slate-800 text-center text-xs text-slate-500">
      &copy; {new Date().getFullYear()} Amar Desh Travel Guide. All rights reserved. Made with ❤️ for Bangladesh.
    </div>
  </footer>
);